(Source ppx)
(Cfg_str project_name oreely)
(Cfg_str project_slug oreely)
(Cfg_str project_description "Ecto-like toolkit for data mapping and language integrated query for OCaml")
(Cfg_str author_name "Alexandre de Souza")
(Cfg_str github_username aleDsz)
(Cfg_str npm_username aleDsz)
(Cfg_str syntax Reason)
